-------------------------------------1st Query----------------------------------------------

CREATE TABLE BOOK(
ID INT PRIMARY KEY,
TITLE VARCHAR(50),
AUTHOR VARCHAR(30),
ISBN BIGINT,
PUBLISHED_DATE DATETIME
);

INSERT INTO BOOK VALUES(1,'MY FIRST SQL BOOK','MARY PARKER',981483029127,'2012-02-22 12:08:17')
INSERT INTO BOOK VALUES(2,'MY SECOND SQL BOOK','JOHN MAYER',857300923713,'1972-07-03 09:22:45')
INSERT INTO BOOK VALUES(3,'MY THIRD SQL BOOK','CARY FLINT',523120967812,'2015-10-18 14:05:44')

SELECT * FROM BOOK 
WHERE AUTHOR LIKE '%ER';

-------------------------------------2st Query----------------------------------------------

CREATE TABLE REVIEWS
(ID INT PRIMARY KEY,
BOOKID INT FOREIGN KEY REFERENCES BOOK(ID),
REVIEWER_NAME  VARCHAR(30),
CONTENT VARCHAR(30),
RATING INT,
PUBLISH_DATE DATETIME 
);

INSERT INTO REVIEWS VALUES(1,1,'JOHN SMITH','MY FIRST REVIEW',4,'2017-12-10 05:50:11')
INSERT INTO REVIEWS VALUES(2,2,'JOHN SMITH','MY SECOND REVIEW',5,'2017-10-13 15:05:12')
INSERT INTO REVIEWS VALUES(3,3,'ALICE REVIEW','ANOTHER REVIEW',1,'2017-10-22 23:47:10')

SELECT * FROM REVIEWS

SELECT B.TITLE,B.AUTHOR,R.REVIEWER_NAME
FROM REVIEWS R LEFT JOIN BOOK B ON R.BOOKID=B.ID

-------------------------------------3rd Query----------------------------------------------

SELECT REVIEWER_NAME FROM REVIEWS
GROUP BY REVIEWER_NAME
HAVING COUNT(REVIEWER_NAME)>1;

-------------------------------------4th Query----------------------------------------------

CREATE TABLE CUSTOMER
(
ID INT PRIMARY KEY,
NAME VARCHAR(30),
AGE INT,
ADDRESS VARCHAR(30),
SALARY FLOAT
);

INSERT INTO CUSTOMER VALUES(1,'RAMESH',32,'AHEMEDABAD',2000.00)
INSERT INTO CUSTOMER VALUES(2,'KHILAN',25,'DELHI',1500.00)
INSERT INTO CUSTOMER VALUES(3,'KAUSHIK',23,'KOTA',2000.00)
INSERT INTO CUSTOMER VALUES(4,'CHAITALI',25,'MUMBAI',65000.00)
INSERT INTO CUSTOMER VALUES(5,'HARDIK',27,'BHOPAL',8500.00)
INSERT INTO CUSTOMER VALUES(6,'KOMAL',22,'MP',4500.00)
INSERT INTO CUSTOMER VALUES(7,'MUFFY',24,'INDORE',10000.00)

SELECT * FROM CUSTOMER

SELECT NAME,ADDRESS FROM CUSTOMER
WHERE ADDRESS LIKE '%O%';

-------------------------------------5th Query----------------------------------------------

CREATE TABLE ORDERS
(OID INT PRIMARY KEY,
DATE DATETIME,
CUSTOMER_ID INT FOREIGN KEY REFERENCES CUSTOMER(ID),
AMOUNT FLOAT
);

INSERT INTO ORDERS VALUES(102,'2009-10-08 00:00:00',3,3000)
INSERT INTO ORDERS VALUES(100,'2009-10-08 00:00:00',3,1500)
INSERT INTO ORDERS VALUES(101,'2009-11-20 00:00:00',2,1500)
INSERT INTO ORDERS VALUES(103,'2008-05-20 00:00:00',4,2060)

SELECT * FROM CUSTOMER

SELECT DATE,COUNT(CUSTOMER_ID)
FROM ORDERS
GROUP BY DATE

-------------------------------------6th Query----------------------------------------------

CREATE TABLE EMPLOYEE
(ID INT PRIMARY KEY,
NAME VARCHAR(30),
AGE INT,
ADDRESS VARCHAR(30),
SALARY FLOAT
);

INSERT INTO EMPLOYEE VALUES(1,'RAMESH',32,'AHEMEDABAD',2000.00)
INSERT INTO EMPLOYEE VALUES(2,'KHILAN',25,'DELHI',1500.00)
INSERT INTO EMPLOYEE VALUES(3,'KAUSHIK',23,'KOTA',2000.00)
INSERT INTO EMPLOYEE VALUES(4,'CHAITALI',25,'MUMBAI',65000.00)
INSERT INTO EMPLOYEE VALUES(5,'HARDIK',27,'BHOPAL',8500.00)
INSERT INTO EMPLOYEE VALUES(6,'KOMAL',22,'MP',NULL)
INSERT INTO EMPLOYEE VALUES(7,'MUFFY',24,'INDORE',NULL)

SELECT * FROM EMPLOYEE 

SELECT LOWER(NAME) FROM EMPLOYEE 
WHERE SALARY IS NULL;

-------------------------------------7th Query----------------------------------------------

CREATE TABLE STUDENTDETAILS
(REGISTERNO INT PRIMARY KEY,
NAME VARCHAR(30),
AGE INT,
QUALIFICATION VARCHAR(20),
MOBILENO BIGINT,
MAIL_ID VARCHAR(20),
LOCATION VARCHAR(20),
GENDER CHAR(1)
);

INSERT INTO STUDENTDETAILS VALUES(2,'SAI',22,'B.E.',9952836777,'sai@gmail.com','chennai','M');
INSERT INTO STUDENTDETAILS VALUES(3,'KUMAR',20,'B.SC',7890125648,'Kumar@gmail.com','Madurai','M');
INSERT INTO STUDENTDETAILS VALUES(4,'SELVI',22,'B.TECH.',8904567342,'selvi@gmail.com','SELAM','F');
INSERT INTO STUDENTDETAILS VALUES(5,'NISHA',25,'M.E.',7834672310,'Nisha@gmail.com','THENI','F');
INSERT INTO STUDENTDETAILS VALUES(6,'SAISARAN',21,'BA.',7890345678,'saran@gmail.com','MADURAI','F');
INSERT INTO STUDENTDETAILS VALUES(7,'TOM',23,'BCA.',8901234675,'Tom@gmail.com','PUNE','M');

SELECT * FROM STUDENTDETAILS

SELECT GENDER,COUNT(GENDER)
FROM STUDENTDETAILS
GROUP BY GENDER

-------------------------------------9th Query----------------------------------------------

CREATE TABLE CUSTOMERS
(CUSTOMER_ID INT PRIMARY KEY,
FIRST_NAME VARCHAR(20),
LAST_NAME VARCHAR(20)
);

DROP TABLE ORDERS;

CREATE TABLE ORDERS
(
ORDER_ID INT PRIMARY KEY,
ORDER_DATE DATE,
AMOUNT FLOAT,
CUSTOMER_ID INT FOREIGN KEY REFERENCES CUSTOMERS(CUSTOMER_ID)
);


INSERT INTO CUSTOMERS VALUES(1,'GEORGE','WASHINGTON')
INSERT INTO CUSTOMERS VALUES(2,'JOHN','ADAMS')
INSERT INTO CUSTOMERS VALUES(3,'THOMAS','JEFFERSON')
INSERT INTO CUSTOMERS VALUES(4,'JAMES','MADISON')
INSERT INTO CUSTOMERS VALUES(5,'JAMES','MONROE')


INSERT INTO ORDERS VALUES(1,'1776-07-04',234.56,1)
INSERT INTO ORDERS VALUES(2,'1776-03-14',78.50,3)
INSERT INTO ORDERS VALUES(3,'1776-05-23',124.00,2)
INSERT INTO ORDERS VALUES(4,'1776-09-03',65.50,3)
INSERT INTO ORDERS VALUES(5,'1776-07-21',26.50,10)
INSERT INTO ORDERS VALUES(6,'1787-11-27',14.40,9)

SELECT * FROM ORDERS

SELECT C.FIRST_NAME,C.LAST_NAME FROM 
CUSTOMERS C
LEFT JOIN ORDERS O
ON C.CUSTOMER_ID=O.CUSTOMER_ID
GROUP BY O.CUSTOMER_ID,C.FIRST_NAME,C.LAST_NAME
HAVING COUNT(O.CUSTOMER_ID)=2


-------------------------------------10th Query----------------------------------------------

SELECT REVERSE(NAME) AS REVERSE_NAME,UPPER(LOCATION) AS LOCATION
FROM STUDENTDETAILS;

-------------------------------------11th Query----------------------------------------------

CREATE VIEW PRODUCTINFO
AS
SELECT O1.PRODUCTNAME,O1.QUANTITY,O2.ORDERNUMBER
FROM ORDER O1
LEFT JOIN ORDERITEM O2
ON O1.ID=O2.ORDERID;

-------------------------------------12th Query----------------------------------------------

SELECT CD.C_NAME FROM STUDENTDETAILS ST
JOIN COURSEREGISTRATION CR 
ON ST.REGISTERNO=CR.REGISTERNO
JOIN COURSEDETAILS CD
ON CD.C_ID=CR.CID
WHERE ST.NAME='NISHA'





